### ISSUE TITLE
Publish to crates.io?

### ISSUE THREAD

**Issue by dgraham** [servo/rust-png#52]
Now that the cargo registry is up and running at [crates.io](https://crates.io), is there interest in publishing this png crate there? There's a [guide available](http://doc.crates.io/crates-io.html), but the steps are really simple:

```
$ cargo login <api-key>
$ cargo package
$ cargo publish
```

Cargo seems to only allow crates to depend on other crates in the registry. It fails when using git dependencies. So I think this needs to live in the registry for other published crates to use it.

I used this library to build https://github.com/dgraham/identicon. The Rust bindings to libpng were super helpful :zap:.

**Comment by slashgrin** [comment]
@dgraham I'd also be interested in having this crate published to crates.io; I have a project that won't even compile most of the time, because there's often no working combination of its various dependencies! :)

I believe this project still tracks the Servo-specific fork of the Rust compiler and standard library, so it might not be trivial for them to maintain a parallel release series. _Maybe_ once Rust 1.0 stabilises some of the smaller Servo dependencies like this one will be able to stick to mainline features without much trouble, but my outsider's understanding of things is that we probably shouldn't expect servo dependencies like this to end up on crates.io before Rust 1.0 lands.

**Comment by jdm** [comment]
We are trying to keep dependencies like this one more up to date with nightlies than Servo these days, and intend to set up Travis to help facilitate that. PRs to upgrade will be happily merged.

**Comment by dgraham** [comment]
Closing as stale.
